
id: am-ssl
version: 0.1.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-net
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-net.git

platforms:
  - id: libc
    abstract: true
    additionalHeaders:
    additionalCSources: 
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    additionalHeaders:
    additionalCSources: 
    gccAdditionalOptions:
    gccAdditionalLibraries:
      - socket
      - amisslstubs
      - amisslauto
  - id: linux-x64
    extends: libc
    gccCommand: gcc
    gccAdditionalLibraries:
      - ssl
      - crypto
  - id: macos
    extends: libc
    gccCommand: gcc -O3
    additionalIncludePaths:
      - c-libs/openssl/include
    gccLibraryPaths:
      - c-libs/openssl/lib
    gccAdditionalOptions:
      - -DOPENSSL_SSL_LIBRARY=c-libs/openssl/lib/libssl.dylib -DOPENSSL_CRYPTO_LIBRARY=c-libs/openssl/lib/libcrypto.3.dylib
    gccAdditionalLibraries:
      - ssl
      - crypto
  - id: macos-arm
    extends: macos
    gccCommand: gcc
    additionalIncludePaths:
      - c-libs/openssl/include
    gccLibraryPaths:
      - c-libs/openssl/lib
    gccAdditionalOptions:
      - -DOPENSSL_SSL_LIBRARY=c-libs/openssl/lib/libssl.dylib -DOPENSSL_CRYPTO_LIBRARY=c-libs/openssl/lib/libcrypto.3.dylib
    gccAdditionalLibraries:
      - ssl
      - crypto
  - id: morphos-ppc
    extends: libc
    gccCommand: ppc-morphos-gcc
    gccAdditionalOptions:
      - -noixemul
  - id: aros-x86-64
    extends: libc
    gccCommand: gcc
    gccAdditionalOptions:
      - -noixemul
buildTargets:
  - id: amigaos_docker_win
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host -i kjeldsenanders/dnf-dev:initial-x86 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_matebook
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host kjeldsenanders/dnf-dev:initial-x86 make -f amigaos.makefile -C /host ${make_target}
#      - docker run -v ${build_dir}:/host -i 265cc923e013 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_macm1
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host -i kjeldsenanders/dnf-dev:initial-x86 make -f amigaos.makefile -C /host all
  - id: macos
    platform: macos
    commands:
      - make -f macos.makefile
  - id: macos-arm
    platform: macos-arm
    commands:
      - make -f macos-arm.makefile
  - id: linux-x64
    platform: linux-x64
  - id: morphos-ppc_docker
    platform: morphos-ppc
    commands:
      - docker run --rm -v "${build_dir}":/work -e USER=$( id -u ) -e GROUP=$( id -g ) -it amigadev/crosstools:ppc-morphos make -f morphos_ppc.makefile -C /work all
  - id: morphos-ppc_docker_win
    platform: morphos-ppc
    commands:
      - docker run --rm -v "${build_dir}":/work -e -i amigadev/crosstools:ppc-morphos make -f morphos-ppc.makefile -C /work all
  - id: aros-x86-64_docker_win
    platform: aros-x86-64
    commands: 
      - docker run --rm -v "${build_dir}":/work -i amigadev/crosstools:x86_64-aros make aros-x86-64.makefile all
