
id: ssl-test
version: 1.0.0
type: application
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-net
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-net.git
  - id: am-ssl
    realm: github
    type: git-repo
    tag: latest
#    branch: master
    url: https://github.com/anderskjeldsen/am-ssl.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:
      - socket
  - id: macos
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:
  - id: linux-x64
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc
      buildPath: /host
  - id: macos
    platform: macos
  - id: linux-x64
    platform: linux-x64
